### ISSUE TITLE
Hydration class mismatch using Layouts (SSR) v1.2.3

### ISSUE THREAD

**Issue by ahmedrangel** [egidiusmengelberg/nuxt-aos#21]
The hydration class mismatch fix in #19 works but for some reason the issue persists when using Layouts (SSR mode).

![image](https://github.com/egidiusmengelberg/nuxt-aos/assets/50090595/8963d668-f161-49d2-8ae8-4b2c7ad4cc99)

See this for reproduction:
https://stackblitz.com/edit/nuxt-starter-x47xa7

nuxt (3.10.2)
nuxt-aos (1.2.3)

**Comment by egidiusmengelberg** [comment]
Mmm, maybe layouts are rendered at a different time. I'll investigate.

**Comment by ahmedrangel** [comment]
> Mmm, maybe layouts are rendered at a different time. I'll investigate.

I tried using the original aos package, just like you use it in your module, but through the plugins folder to test some of the [Nuxt App Hooks](https://nuxt.com/docs/api/advanced/hooks#app-hooks-runtime).

I also got the hydration class mismatch issue using `app:mounted`, but I got it working after testing with hooks that comes after `app:mounted` such as `app:suspense:resolve` and `page:finish`.

Maybe one of those could be the solution?

You can check it here:
https://stackblitz.com/edit/nuxt-starter-qt3scw?file=plugins%2Faos.js

**Comment by egidiusmengelberg** [comment]
Ah okay, Ill create a PR right now. I think page:finish would be a good solution.

**Comment by egidiusmengelberg** [comment]
```page:finish``` did not work in my tests, It removed all the elements from the page.

```app:suspense:resolve``` did work, and is released in 1.2.4 so it should be fine now.

If it's still broken, please create a new issue.
