### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by suchorski** [egidiusmengelberg/nuxt-aos#33]
Using nuxt v3.12.2 and nuxt-aos v1.2.4

Failed to resolve dependency: aos, present in 'optimizeDeps.include'

Uncaught SyntaxError: The requested module 'http://localhost:6060/_nuxt/node_modules/.pnpm/lodash.throttle@4.1.1/node_modules/lodash.throttle/index.js?v=cf0afada' doesn't provide an export named: 'default'

**Comment by Bukunmikuti** [comment]
Same issue here, using the Nuxt module.

**Comment by suchorski** [comment]
I'm using the AOS library, making a plugin to provide the AOS to useNuxt and initializing in onMounted inside app.vue

**Comment by egidiusmengelberg** [comment]
yeah having the issue aswell. even after updating the package. still figuring out how to fix it.

when developing the module everything works fine. Maybe using nuxt layers instead of modules is a better idea
