### ISSUE TITLE
Does not provide an export named 'default' error

### ISSUE THREAD

**Issue by JeremyMees** [egidiusmengelberg/nuxt-aos#4]
I've created [reproduction](https://stackblitz.com/edit/nuxt-starter-cc7dxp?file=app.vue) for the issue.
It's just a clean nuxt 3.7 install and i followed the documentation to install nuxt-aos.
The page does not load anymore

**Comment by egidiusmengelberg** [comment]
I tried to fix it but it didn't work. Seems to be an issue with importing aos. Because it does not have a export.

I'll keep trying to fix it.

**Comment by JeremyMees** [comment]
I installed aos@next directly without the nuxt module and that worked. So it seems to me that's not the problem. But yeah I could be wrong because I'm no expert on this.

**Comment by egidiusmengelberg** [comment]
Yeah thats weird. I tried it with aos@next. But that didn't work. Still investigating.

**Comment by egidiusmengelberg** [comment]
There is a PR ready to be merged at the AOS library, https://github.com/michalsnik/aos/pull/423. But it seems the project is dead. Last update was 5 years ago. I'll try and email the author next week. If that doesn't work I could create a fork and update it myself. But that would not be a elegant solution. Anybody any ideas?

**Comment by Islam8Bahaa** [comment]
You can try this [nuxt3-aos](https://www.npmjs.com/package/nuxt3-aos) Its working good

**Comment by egidiusmengelberg** [comment]
Fixed in v1.2.2
