### ISSUE TITLE
 esm js error

### ISSUE THREAD

**Issue by tolgahanbeyazoglu** [egidiusmengelberg/nuxt-aos#7]
@egidiusmengelberg  When I add the dependency, I encounter this error after the project runs, what is the reason?

`aos.esm.js?v=56ed4182:2 Uncaught SyntaxError: The requested module '/_nuxt/node_modules/lodash.debounce/index.js?v=56ed4182' does not provide an export named 'default' (at aos.esm.js?v=56ed4182:2:8)`

**Comment by egidiusmengelberg** [comment]
Yeah I know, please read issue #6. Because of a busy schedule i'm currently not able to fix the issue. If anyone wants to create a PR I would really appreciate it.

**Comment by egidiusmengelberg** [comment]
There is a PR ready to be merged at the AOS library, https://github.com/michalsnik/aos/pull/423. But it seems the project is dead. Last update was 5 years ago. I'll try and email the author next week. If that doesn't work I could create a fork and update it myself. But that would not be a elegant solution. Anybody any ideas?

**Comment by 17630966776** [comment]
You can try this [nuxt3-aos](https://www.npmjs.com/package/nuxt3-aos)

**Comment by tolgahanbeyazoglu** [comment]
Yes, it works smoothly thanks to the module you specified.
